name = "JolinRegistry"
uuid = "d8b8f4a5-446a-4289-bdd3-2aada5c65e7a"
repo = "git@github.com:jolin-io/JolinRegistry.jl.git"

[packages]
5b0b4ef8-f4e6-4363-b674-3f031f7b9530 = { name = "JolinPluto", path = "J/JolinPluto" }
