name = "JolinRegistry"
uuid = "d8b8f4a5-446a-4289-bdd3-2aada5c65e7a"
repo = "https://github.com/jolin-io/JolinRegistry.jl"

[packages]
41f5a839-9417-47e4-8d5e-d13fd1915f06 = { name = "JolinPlutoCICD", path = "J/JolinPlutoCICD" }
5b0b4ef8-f4e6-4363-b674-3f031f7b9530 = { name = "JolinPluto", path = "J/JolinPluto" }
87100c7f-5f96-485a-944e-f6ba66ec4971 = { name = "Jolin", path = "J/Jolin" }
